services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - vendor:/app/vendor
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command: php -S 0.0.0.0:8080 -t /app/public
    networks:
      - fruits-vegetables-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - fruits-vegetables-network

networks:
  fruits-vegetables-network:
volumes:
  vendor: